# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10)),
                ('person_to_meet', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('from_time', models.CharField(max_length=300)),
                ('to_time', models.CharField(max_length=300)),
                ('visitor_image', models.FileField(upload_to='visitors/')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
